name: Build

on: [push, pull_request]  # Запускать при пушах и пулл-реквестах

jobs:
  build:
    runs-on: macos-latest  # Используем последнюю версию macOS

    steps:
    - uses: actions/checkout@v4

    - name: Compile library
      run: |
        clang++ -std=c++20 -dynamiclib -o libmylib.dylib mylib.cpp

    - name: Compile program
      run: |
        clang++ -std=c++20 -L. -lmylib -o main main.cpp

    - name: Run program
      run: |
        ./main